### ISSUE TITLE
Output Comments

### ISSUE THREAD

**Issue by JamesKindon** [msfreaks/Citrix.WEM#1]
If i export a file using the following for example "Out-file | C:\Temp\James.xml
WEM will not load the file - Might be worth forcing a filename that WEM can import

If i use the standard required name of Out-File | C:\Temp\VUEMApplications.xml its fine

if i run just the standard New-VUEMApplicationsXML with no outfile (As per exampled) then you get no out file - might be worth forcing an out-file or using current execution path?

**Comment by msfreaks** [comment]
I had a lot of doubts about how to handle the output.
As I am working on the GPO convert function, I come to realize I need several XML output files, which I then basically need to force as well.
I'll see if I can implement the forced output when I get to outputting the different XML files.
Thanks for the feedback!

**Comment by JamesKindon** [comment]
I say force it - I had to do similar when writing the WEM config dump/doco - had to force the specific file type no matter what a user put in - covers yourself for fat fingering and if people don't want to specify a path - just dump it to where they execute the script from :)

few bits of fun i had with WEM here
https://github.com/JamesKindon/CitrixWEMDoc
https://github.com/JamesKindon/WEMHydrationKit

**Comment by msfreaks** [comment]
Took your advice James.
Two parameters added:
-OutputPath (defaults to current folder if ommitted)
-OutputFilename (defaults to VUEMApplications.xml if ommitted)
