### ISSUE TITLE
New Module Feedback

### ISSUE THREAD

**Issue by JamesKindon** [msfreaks/Citrix.WEM#2]
Once again this is awesome work, a couple of fun ones for you 

1. The Import-VUEMActionsFromGPO doesn't handle registry collections within a GPO object - if its a single registry value its good - but the collections just results in a top level object representing the actual collection. 

2. The Import-VUEMActionsFromGPO function currently when dealing with network drives outputs the WEM Actions with a name representing the drive letter in the GPP. I feel it might make a bit more sense to maybe create the WEM Action with the "Name" matching the "Location" attribute within the GPP?

3. And this one is more of a feature request - given that you are able to pull all this data out of the backups, it would be nice to have a switch that could output item level targeting to a csv file :)

I can provide you some pretty hairy GPO objects offline if you want some nasty ones to test against

**Comment by msfreaks** [comment]
Hi James,
Dealing with collections turned out to be a bit tricky for me so I choose to create top level actions for all items in a collection. I’ll see what I can come up with for the next version.
By location for mapped drives you mean the UNC path?
And yes please, I’d love to have some real GPOs to test against!

Cheers

Arjan

**Comment by JamesKindon** [comment]
Hey Arjan,

I can only imagine - collections are horrible things to track through and they allow for lots of duplicates which is going to be a challenge... happy to help if you need extra eyes

By Location i mean the UNC path yes - i think the GPP stores this as "Location" within its config - makes it nice and easy to read within WEM, currently with the import of lots of drives, you just end up with the name G, D, F if nothing descriptive has been added into GPP - the UNC path is always unique and clear

Ill provide you a stack of GPO's offline and we can give them a belting - outside of the above, the script went nicely through them first pass :)

James
